=== Flop1908/ESGI5AL2_XML_Databases/XML-php/databases.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <xs:import namespace="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="xsi.xsd"/>
  <!-- élément racine : Liste de bases de données -->
  <xs:element name="databases">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="database"/>
        <xs:element ref="metadata"/>
      </xs:sequence>
	  <!-- Reference au schéma -->
      <xs:attribute ref="xsi:noNamespaceSchemaLocation" use="required"/>
    </xs:complexType>
  </xs:element>
  <!-- Les meta-informations de la liste de base de données -->
  <xs:element name="metadata">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="author"/>
        <xs:element ref="creation_date"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- Créateur de la liste de bases de données -->
  <xs:element name="author">
    <xs:complexType/>
  </xs:element>
  <!-- Date de la création de la liste de bases de données -->
  <xs:element name="creation_date">
    <xs:complexType/>
  </xs:element>
  <!-- Représente une base de données -->
  <xs:element name="database">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tables"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- Liste des tables d'un base de données -->
  <xs:element name="tables">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="table"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- Une table d'une base de données -->
  <xs:element name="table">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="columns"/>
        <xs:element ref="rows"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- Liste des columns d'une table -->
  <xs:element name="columns">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="column"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- Une column d'une table (une table doit avoir au moins une colonne)-->
  <xs:element name="column">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="type"/>
        <xs:element minOccurs="0" ref="reference"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- Type d'information qui sera stockée dans cette column -->
  <xs:element name="type" type="xs:NCName"/>
  <!-- Element servant de lien entre deux champs -->
  <xs:element name="reference">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="table_reference"/>
        <xs:element ref="column_reference"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- Nom de la table sur laquelle faire la référence -->
  <xs:element name="table_reference" type="xs:NCName"/>
  <!-- Nom du champ de la table sur laquelle faire la référence -->
  <xs:element name="column_reference" type="xs:NCName"/>
  <!-- Liste des lignes contenant les valeurs d'une table -->
  <xs:element name="rows">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="row"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- Element représentant une ligne de valeur d'une table -->
  <xs:element name="row">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="fields"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- Liste des champs d'une ligne -->
  <xs:element name="fields">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="field"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- Contenu d'un champ -->
  <xs:element name="field">
    <xs:complexType mixed="true">
	  <!-- Nom de la colonne correspondant au champ -->
      <xs:attribute name="column_name" type="xs:NCName"/>
	  <!-- Ancien nom pour raison de compatibilité -->
      <xs:attribute name="name" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <!-- nom d'un élément -->
  <xs:element name="name" type="xs:NCName"/>
</xs:schema>

=== Flop1908/ESGI5AL2_XML_Databases/XML-java/database.xml
<?xml version="1.0" encoding="ISO-8859-1"?><databases xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="databases.xsd">	<metadata>		<author>root</author>		<creation_date>10-11-2013</creation_date>	</metadata>	<database>				<name>Project Series</name>		<tables>			<table>				<name>series</name>				<columns>					<column>						<name>id_serie</name>						<type>primary key</type>					</column>					<column>						<name>nom_serie</name>						<type>string</type>					</column>					<column>						<name>description_serie</name>						<type>string</type>					</column>				</columns>				<rows>					<row>						<fields>							<field column_name="id_serie">1</field>							<field column_name="nom_serie">Strike Back</field>							<field column_name="description_serie">An adaptation of SAS soldier Chris Ryan's novel.</field>						</fields>					</row>					<row>						<fields>							<field column_name="id_serie">2</field>							<field column_name="nom_serie">Person of interest</field>							<field column_name="description_serie">Person of Interest is a crime thriller about a presumed dead former-CIA agent, Reese, who teams up with a mysterious billionaire, Finch, to prevent violent crimes by using their own brand of vigilante justice.</field>						</fields>					</row>				</rows>				</table>			<table>				<name>episodes</name>				<columns>					<column>						<name>id_episode</name>						<type>primary key</type>					</column>					<column>						<name>numero_saison</name>						<type>int</type>					</column>					<column>						<name>numero_episode</name>						<type>int</type>					</column>					<column>						<name>nom_episode</name>						<type>string</type>					</column>					<column>						<name>description_episode</name>						<type>string</type>					</column>					<column>						<name>id_serie</name>						<type>foreign key</type>						<reference>							<table_reference>series</table_reference>							<column_reference>id_serie</column_reference>						</reference>					</column>				</columns>				<rows>					<row>						<fields>							<field column_name="id_episode">1</field>							<field column_name="numero_saison">1</field>							<field column_name="numero_episode">1</field>							<field column_name="nom_episode">Pilot</field>							<field column_name="description_episode">Reese and Finch must figure out whether a young prosecutor is a victim or a suspect.</field>							<field column_name="id_serie">2</field>						</fields>					</row>					<row>						<fields>							<field column_name="id_episode">2</field>							<field column_name="numero_saison">2</field>							<field column_name="numero_episode">1</field>							<field column_name="nom_episode">The Contingency</field>							<field column_name="description_episode">Reese asks Detectives Carter and Fusco for help finding Finch, who was kidnapped by his nemesis.</field>							<field column_name="id_serie">2</field>						</fields>					</row>					<row>						<fields>							<field column_name="id_episode">3</field>							<field column_name="numero_saison">1</field>							<field column_name="numero_episode">1</field>							<field column_name="nom_episode">Episode 1</field>							<field column_name="description_episode">Still haunted by the memory of a disastrous Special Forces mission which he led in 2003, John Porter is given an opportunity to redeem himself by returning to Iraq to rescue a kidnapped TV reporter.</field>							<field column_name="id_serie">1</field>						</fields>					</row>					<row>						<fields>							<field column_name="id_episode">4</field>							<field column_name="numero_saison">2</field>							<field column_name="numero_episode">1</field>							<field column_name="nom_episode">Project Dawn, Episode 1</field>							<field column_name="description_episode">British sergeant Michael Stonebridge recruits help from Ex-Delta Force operative Damien Scott when an agent named John Porter is kidnapped by a Pakistani terrorist.</field>							<field column_name="id_serie">1</field>						</fields>					</row>				</rows>				</table>			<table><name>Link</name><columns><column><name>id</name><type>primary key</type></column><column><name>txt</name><type>string</type></column></columns><rows/></table><table><name>ProjectTest</name><columns><column><name>id</name><type>primary key</type></column><column><name>info</name><type>string</type></column></columns><rows/></table><table><name/><columns/><rows/></table><table><name></name><columns/><rows/></table></tables>	</database><database><name>Pr</name><tables/></database></databases>
